[etcd]
pitaya.cluster.sd.etcd.dialtimeout = "5s"
pitaya.cluster.sd.etcd.endpoints = "localhost:2379"
pitaya.cluster.sd.etcd.grantlease.maxretries = 15
pitaya.cluster.sd.etcd.grantlease.retryinterval = "5s"
pitaya.cluster.sd.etcd.grantlease.timeout = "60s"
pitaya.cluster.sd.etcd.heartbeat.log = false
pitaya.cluster.sd.etcd.heartbeat.ttl = "60s"
pitaya.cluster.sd.etcd.prefix = "pitaya/"
pitaya.cluster.sd.etcd.revoke.timeout = "5s"
pitaya.cluster.sd.etcd.syncservers.interval = "120s"
pitaya.cluster.sd.etcd.shutdown.delay = "10ms"
pitaya.cluster.sd.etcd.servertypeblacklist = []
pitaya.cluster.sd.etcd.syncserversparallelism = 10

[etcd.path]
gate = "/"
